import L from 'leaflet'; import 'leaflet/dist/leaflet.css'; import * as turf from '@turf/turf'; import shpwrite from 'shp-write'; import './style.css';
const map=L.map('map',{zoomControl:true}).setView([-17.79,-50.92],13);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
const satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:20,attribution:'Tiles © Esri'}).addTo(map);
L.control.layers({'Satellite':satellite},{'Road map':L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19})}).addTo(map);
let state=JSON.parse(localStorage.getItem('fieldLineBuilder')||'null')||{name:'',boundary:[],segments:[],ab:[],guides:[],guideName:'Main rows',width:9};
let mode=null, boundaryLine, polygon, abLine, guideLayer=L.layerGroup().addTo(map), vertexLayer=L.layerGroup().addTo(map), selectedSegment=-1;
function save(){localStorage.setItem('fieldLineBuilder',JSON.stringify(state))} function redraw(){ if(boundaryLine)map.removeLayer(boundaryLine);if(polygon)map.removeLayer(polygon);vertexLayer.clearLayers(); if(state.boundary.length){boundaryLine=L.polyline(state.boundary,{weight:4}).addTo(map);state.boundary.forEach((p,i)=>L.circleMarker(p,{radius:6}).addTo(vertexLayer).on('click',e=>{L.DomEvent.stopPropagation(e);selectSegment(Math.max(0,i-1))}));if(state.boundary.length>2)polygon=L.polygon(state.boundary,{weight:2,fillOpacity:.08}).addTo(map)} if(abLine)map.removeLayer(abLine);if(state.ab.length===2)abLine=L.polyline(state.ab,{weight:4,dashArray:'8 6'}).addTo(map);guideLayer.clearLayers();state.guides.forEach(g=>L.polyline(g,{weight:2,opacity:.8}).addTo(guideLayer)); renderSegments();document.querySelector('#fieldName').textContent=state.name||'No field selected';save()}
function renderSegments(){const box=document.querySelector('#segments');box.innerHTML='<h4>Boundary lines</h4>';for(let i=0;i<Math.max(0,state.boundary.length-(state.closed?0:1));i++){let b=document.createElement('button');b.textContent=(state.segments[i]?.name)||`Border ${i+1}`;if(i===selectedSegment)b.classList.add('selected');b.onclick=()=>selectSegment(i);box.appendChild(b)}}function selectSegment(i){selectedSegment=i;document.querySelector('#segmentName').value=state.segments[i]?.name||'';renderSegments()}
map.on('click',e=>{if(mode==='boundary'){state.boundary.push([e.latlng.lat,e.latlng.lng]);state.closed=false;redraw()}else if(mode==='ab'){state.ab.push([e.latlng.lat,e.latlng.lng]);if(state.ab.length===2)mode=null;redraw()}});
document.querySelector('#newField').onclick=()=>{const n=prompt('Field name');if(!n)return;state={name:n,boundary:[],segments:[],ab:[],guides:[],guideName:'Main rows',width:9};selectedSegment=-1;redraw()};
document.querySelector('#drawBoundary').onclick=()=>mode='boundary';document.querySelector('#finishBoundary').onclick=()=>{if(state.boundary.length<3)return alert('Add at least 3 boundary points.');state.closed=true;mode=null;while(state.segments.length<state.boundary.length)state.segments.push({name:`Border ${state.segments.length+1}`});redraw();map.fitBounds(L.latLngBounds(state.boundary),{padding:[20,20]})};document.querySelector('#undoPoint').onclick=()=>{state.boundary.pop();redraw()};document.querySelector('#clearBoundary').onclick=()=>{if(confirm('Clear this boundary?')){state.boundary=[];state.segments=[];state.guides=[];redraw()}};document.querySelector('#renameSegment').onclick=()=>{if(selectedSegment<0)return alert('Select a boundary point/line first.');state.segments[selectedSegment]={name:document.querySelector('#segmentName').value||`Border ${selectedSegment+1}`};redraw()};
document.querySelector('#drawAB').onclick=()=>{state.ab=[];mode='ab';redraw()};document.querySelector('#clearGuides').onclick=()=>{state.ab=[];state.guides=[];redraw()};
document.querySelector('#generate').onclick=()=>{if(!state.closed||state.ab.length!==2)return alert('Finish the boundary and draw an AB line first.');const width=+document.querySelector('#width').value;if(!(width>0))return;state.width=width;state.guideName=document.querySelector('#guideName').value||'Main rows';const ring=state.boundary.map(([lat,lng])=>[lng,lat]);ring.push(ring[0]);const poly=turf.polygon([ring]);const [a,b]=state.ab.map(([lat,lng])=>turf.point([lng,lat]));const bearing=turf.bearing(a,b);const bbox=turf.bbox(poly);const diag=turf.distance([bbox[0],bbox[1]],[bbox[2],bbox[3]],{units:'meters'});const center=turf.center(poly);let lines=[];for(let off=-diag;off<=diag;off+=width){let c=turf.destination(center,off,bearing+90,{units:'meters'});let p1=turf.destination(c,diag*2,bearing+180,{units:'meters'}),p2=turf.destination(c,diag*2,bearing,{units:'meters'});let line=turf.lineString([p1.geometry.coordinates,p2.geometry.coordinates]);let split=turf.lineSplit(line,turf.polygonToLine(poly));for(const f of split.features){const mid=turf.along(f,turf.length(f)/2);if(turf.booleanPointInPolygon(mid,poly)){lines.push(f.geometry.coordinates.map(([lng,lat])=>[lat,lng]))}}}state.guides=lines;document.querySelector('#guideInfo').textContent=`${lines.length} passes generated • ${width.toFixed(2)} m • ${state.guideName}`;redraw()};
function geo(){let fs=[];if(state.closed){let ring=state.boundary.map(([lat,lng])=>[lng,lat]);ring.push(ring[0]);fs.push(turf.polygon([ring],{type:'boundary',field:state.name}))}state.boundary.forEach((p,i)=>{if(!state.closed&&i===state.boundary.length-1)return;let q=state.boundary[(i+1)%state.boundary.length];fs.push(turf.lineString([[p[1],p[0]],[q[1],q[0]]],{type:'border',name:state.segments[i]?.name||`Border ${i+1}`}))});state.guides.forEach((g,i)=>fs.push(turf.lineString(g.map(([lat,lng])=>[lng,lat]),{type:'guidance',set:state.guideName,pass:i+1,width_m:state.width})));return turf.featureCollection(fs)}
document.querySelector('#geojson').onclick=()=>download(new Blob([JSON.stringify(geo(),null,2)],{type:'application/geo+json'}),`${safe(state.name)}.geojson`);document.querySelector('#shapefile').onclick=()=>{try{const opts={folder:safe(state.name)||'field',types:{point:'points',polygon:'boundary',line:'lines'}};shpwrite.download(geo(),opts)}catch(e){console.error(e);alert('Shapefile export failed on this browser. Use GeoJSON backup for now.') }};function safe(s='field'){return s.trim().replace(/[^a-z0-9_-]+/gi,'_')||'field'}function download(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.tab).classList.add('active');setTimeout(()=>map.invalidateSize(),100)});redraw();
