import L from 'leaflet';import 'leaflet/dist/leaflet.css';import * as turf from '@turf/turf';import shpwrite from 'shp-write';import './style.css';
const road=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxNativeZoom:19,maxZoom:24,attribution:'© OpenStreetMap'}),sat=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxNativeZoom:17,maxZoom:24,keepBuffer:4,updateWhenZooming:false,attribution:'© Esri'});const map=L.map('map',{layers:[sat],maxZoom:24}).setView([-17.79,-50.92],13);L.control.layers({Satellite:sat,'Road map':road},null,{collapsed:true}).addTo(map);
const $=s=>document.querySelector(s),drawer=$('#drawer'),home=$('#homeActions'),mapBar=$('#mapBar'),pointMenu=$('#pointMenu');const emptyField=(name='')=>({id:Date.now()+Math.random(),name,boundary:[],sections:[],stage:'home',width:9,borderPasses:3,guidanceSets:[]});let legacy=JSON.parse(localStorage.getItem('flb13')||'null'),DB=JSON.parse(localStorage.getItem('flbFields')||'null');if(!DB){DB={fields:legacy&&legacy.name?[{...legacy,id:legacy.id||Date.now()}]:[],currentId:legacy&&legacy.name?(legacy.id||Date.now()):null}}let S=DB.fields.find(f=>f.id===DB.currentId)||emptyField();let mode=null,selected=-1,first=-1,op=null,suppressNextMapTap=false,layer=L.layerGroup().addTo(map),guide=L.layerGroup().addTo(map),handle=null,polyLayer=null,dotMarkers=[],editHistory=[];
function save(){if(S&&S.name){let i=DB.fields.findIndex(f=>f.id===S.id);if(i>=0)DB.fields[i]=S;else DB.fields.push(S);DB.currentId=S.id}localStorage.setItem('flbFields',JSON.stringify(DB));localStorage.setItem('flb13',JSON.stringify(S))}function open(html){removeHandle();hidePointMenu();mapBar.classList.add('hidden');drawer.innerHTML=html;drawer.classList.remove('hidden');home.classList.add('hidden')}function close(){drawer.classList.add('hidden')}function ring(){let r=S.boundary.map(([a,b])=>[b,a]);if(r.length)r.push(r[0]);return r}function poly(){return S.boundary.length>2?turf.polygon([ring()]):null}function area(){return poly()?turf.area(poly())/10000:0}
function forwardIdx(a,b){let out=[a],i=a,n=S.boundary.length;while(i!==b){i=(i+1)%n;out.push(i);if(out.length>n+1)break}return out}function pathMeters(arr){let d=0;for(let k=1;k<arr.length;k++)d+=turf.distance([S.boundary[arr[k-1]][1],S.boundary[arr[k-1]][0]],[S.boundary[arr[k]][1],S.boundary[arr[k]][0]],{units:'meters'});return d}function idxs(a,b){let f=forwardIdx(a,b),r=forwardIdx(b,a).reverse();return pathMeters(f)<=pathMeters(r)?f:r}
function redraw(){layer.clearLayers();guide.clearLayers();dotMarkers=[];polyLayer=null;if(S.boundary.length){polyLayer=L.polygon(S.boundary,{color:'#1683ff',weight:3,fillOpacity:.07}).addTo(layer);if(['draw','locked','edit'].includes(S.stage))S.boundary.forEach((p,i)=>{let m=L.circleMarker(p,{radius:i===first?8:6,color:i===first?'#f0a000':'#1683ff',weight:3,fillColor:'#fff',fillOpacity:1,bubblingMouseEvents:false}).addTo(layer);dotMarkers[i]=m;m.on('click',e=>{L.DomEvent.stopPropagation(e);pointClick(i,e)})});S.sections.forEach(s=>L.polyline(idxs(s.start,s.end).map(i=>S.boundary[i]),{color:'#f0a000',weight:5,opacity:.7,interactive:false}).addTo(layer))}for(const set of S.guidanceSets||[]){for(const g of set.lines)L.polyline(g,{color:set.kind==='headland'?'#e18a00':'#27633f',weight:2,interactive:false}).addTo(guide)}$('#fieldTitle').textContent=S.name?`${S.name} • ${area().toFixed(2)} ha`:'';save()}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#findMe').onclick=()=>map.locate({setView:true,maxZoom:20,enableHighAccuracy:true});map.on('locationfound',e=>L.circleMarker(e.latlng,{radius:7,color:'#173f2a',fillOpacity:1}).addTo(layer).bindTooltip(`±${Math.round(e.accuracy)} m`).openTooltip());map.on('locationerror',()=>alert('Allow location permission and try again.'));
$('#createNew').onclick=()=>newField();$('#fieldsHome').onclick=showFieldsHome;function newField(){open(`<h2>Create New Field</h2><label>Field name<input id="nm" placeholder="Field name"></label><button id="next" class="primary">Continue</button>`);$('#next').onclick=()=>{let n=$('#nm').value.trim();if(!n)return;S=emptyField(n);save();chooseMethod()}}
function chooseMethod(){open(`<h2>${escapeHtml(S.name)}</h2><p>How do you want to create the field boundary?</p><div class="row"><button id="manual" class="primary">Manual</button><button id="gps">GPS</button></div>`);$('#manual').onclick=()=>drawScreen();$('#gps').onclick=()=>alert('GPS boundary recording is the next feature. Manual creation is ready now.')}
function setMapBar(html){drawer.classList.add('hidden');home.classList.add('hidden');mapBar.innerHTML=html;mapBar.classList.remove('hidden')}
function drawScreen(){removeHandle();hidePointMenu();S.stage='draw';mode='draw';setMapBar(`<button id="undo" ${S.boundary.length?'':'disabled'}>↶ Undo</button><span id="cnt">${S.boundary.length} points</span><button id="lock" class="primary">Save</button>`);$('#undo').onclick=()=>{removeHandle();S.boundary.pop();redraw();drawScreen()};$('#lock').onclick=()=>{if(S.boundary.length<3)return alert('Add at least 3 points.');removeHandle();mode=null;S.stage='locked';sectionScreen()};redraw()}
function nearestPointAt(latlng,pixels=28){let q=map.latLngToContainerPoint(latlng),best=-1,dist=Infinity;S.boundary.forEach((p,i)=>{let d=q.distanceTo(map.latLngToContainerPoint(p));if(d<dist){dist=d;best=i}});return dist<=pixels?best:-1}
map.on('click',e=>{if(suppressNextMapTap){suppressNextMapTap=false;return}hidePointMenu();if(handle){removeHandle();redraw();return}if(S.stage==='draw'&&mode==='draw'){let near=nearestPointAt(e.latlng);if(near>=0){showDragHandle(near);return}S.boundary.push([e.latlng.lat,e.latlng.lng]);redraw();let c=$('#cnt'),u=$('#undo');if(c)c.textContent=`${S.boundary.length} points`;if(u)u.disabled=false}else if(mode==='ab'){S._ab=(S._ab||[]).concat([[e.latlng.lat,e.latlng.lng]]);if(S._ab.length===2){mode=null;guidanceOptions('ab')}}});
function pointClick(i,e){if(S.stage==='draw'){showDragHandle(i);return}if(S.stage!=='locked')return;if(op&&first>=0){if(first===i){cancelSectionChoice();return}let a=first,b=i;hidePointMenu();applySection(a,b);return}first=i;showPointMenu(i,e)}
function showDragHandle(i){removeHandle();selected=i;let icon=L.divIcon({className:'drag-handle-wrap',html:'<div class="drag-stem"></div><div class="drag-handle">↔<br>↕</div>',iconSize:[76,76],iconAnchor:[12,12]});handle=L.marker(S.boundary[i],{icon,draggable:true,zIndexOffset:1000,autoPan:true}).addTo(map);handle.on('dragstart',()=>{suppressNextMapTap=true});handle.on('drag',ev=>{let q=ev.target.getLatLng();S.boundary[i]=[q.lat,q.lng];if(dotMarkers[i])dotMarkers[i].setLatLng(q);if(polyLayer)polyLayer.setLatLngs(S.boundary)});handle.on('dragend',()=>{save();removeHandle();redraw();setTimeout(()=>suppressNextMapTap=false,80)});}
function removeHandle(){if(handle){map.removeLayer(handle);handle=null}selected=-1}
function showPointMenu(i,e){removeHandle();first=i;redraw();let pt=map.latLngToContainerPoint(S.boundary[i]);pointMenu.style.left=Math.max(8,Math.min(window.innerWidth-220,pt.x+16))+'px';pointMenu.style.top=Math.max(82,Math.min(window.innerHeight-170,pt.y-18))+'px';pointMenu.classList.remove('hidden')}
function hidePointMenu(){pointMenu.classList.add('hidden')}
pointMenu.querySelectorAll('[data-op]').forEach(b=>b.onclick=e=>{e.stopPropagation();op=b.dataset.op;hidePointMenu();redraw()});
function cancelSectionChoice(){first=-1;op=null;hidePointMenu();redraw()}
function sectionScreen(){removeHandle();hidePointMenu();S.stage='locked';mode=null;setMapBar(`<button id="backPoints">← Back</button><button id="undoEdit" ${editHistory.length?'':'disabled'}>↶ Undo</button><button id="saveField" class="primary">Save</button>`);$('#backPoints').onclick=()=>{first=-1;op=null;drawScreen()};$('#undoEdit').onclick=undoEdit;$('#saveField').onclick=()=>{S.stage='saved';first=-1;op=null;hidePointMenu();mapBar.classList.add('hidden');redraw();fieldScreen()};redraw()}
function snapshotEdit(){editHistory.push({boundary:S.boundary.map(p=>p.slice()),sections:S.sections.map(s=>({...s}))});if(editHistory.length>30)editHistory.shift()}
function undoEdit(){let h=editHistory.pop();if(!h)return;S.boundary=h.boundary;S.sections=h.sections;first=-1;op=null;redraw();sectionScreen()}
function applySection(a,b){if(!op)return;let path=idxs(a,b);snapshotEdit();if(op==='name'){let n=prompt('Border name');if(!n){editHistory.pop();cancelSectionChoice();return}let key=path.join(',');let old=S.sections.find(s=>idxs(s.start,s.end).join(',')===key);if(old)old.name=n;else S.sections.push({start:a,end:b,name:n})}else if(op==='straight'){let p0=S.boundary[path[0]],p1=S.boundary[path[path.length-1]],n=path.length-1;for(let k=1;k<n;k++){let t=k/n;S.boundary[path[k]]=[p0[0]+(p1[0]-p0[0])*t,p0[1]+(p1[1]-p0[1])*t]}}else if(op==='smooth'){let pts=path.map(i=>S.boundary[i].slice());for(let pass=0;pass<2;pass++){let cp=pts.map(x=>x.slice());for(let k=1;k<pts.length-1;k++)cp[k]=[(pts[k-1][0]+2*pts[k][0]+pts[k+1][0])/4,(pts[k-1][1]+2*pts[k][1]+pts[k+1][1])/4];pts=cp}pts.forEach((p,k)=>S.boundary[path[k]]=p)}first=-1;op=null;redraw();sectionScreen()}
function fieldScreen(){open(`<h3>${escapeHtml(S.name)}</h3><div class="status">${area().toFixed(2)} ha • ${S.sections.length} named borders</div><div class="field-actions"><button id="borders">Borders</button><button id="headlands">Border Passes</button><button id="guidance" class="primary">Guidance</button><button id="editGuidance">Edit Guidance</button><button id="more">More ···</button></div>`);$('#borders').onclick=bordersMenu;$('#headlands').onclick=borderPassMenu;$('#guidance').onclick=guidanceMenu;$('#editGuidance').onclick=editGuidanceMenu;$('#more').onclick=moreMenu;redraw()}
function bordersMenu(){open(`<h3>Saved Borders</h3>${S.sections.length?`<div class="section-list">${S.sections.map((s,i)=>`<button data-border="${i}">${escapeHtml(s.name)}</button>`).join('')}</div>`:'<p>No named borders yet.</p>'}<div class="row"><button id="editSections">Edit Boundaries</button><button id="back">Back</button></div>`);document.querySelectorAll('[data-border]').forEach(b=>b.onclick=()=>{let s=S.sections[+b.dataset.border],pts=idxs(s.start,s.end).map(i=>S.boundary[i]);map.fitBounds(L.latLngBounds(pts),{padding:[55,55],maxZoom:20});close()});$('#editSections').onclick=()=>{S.stage='locked';sectionScreen()};$('#back').onclick=fieldScreen}
function borderPassMenu(){open(`<h3>Border Passes</h3><p>Create the passes planted around the outside of the field.</p><label>Implement width (m)<input id="w" type="number" step="0.01" value="${S.width||9}"></label><label>Number of border passes<input id="bp" type="number" min="0" step="1" value="${S.borderPasses??3}"></label><button id="make" class="primary">Create / Update Border Passes</button><button id="back">Back</button>`);$('#make').onclick=()=>{S.width=+$('#w').value||9;S.borderPasses=Math.max(0,+$('#bp').value||0);makeHeadlands();save();fieldScreen()};$('#back').onclick=fieldScreen}
function moreMenu(){open(`<h3>Field Options</h3><div class="field-actions"><button id="export">Export</button><button id="editSections">Edit Boundaries</button><button id="fields">All Fields</button></div><button id="back">Back</button>`);$('#export').onclick=exportScreen;$('#editSections').onclick=()=>{S.stage='locked';sectionScreen()};$('#fields').onclick=showFieldsHome;$('#back').onclick=fieldScreen}
function makeHeadlands(){S.guidanceSets=S.guidanceSets.filter(x=>x.kind!=='headland');let p=poly(),lines=[];for(let i=0;i<S.borderPasses;i++){let d=-(i+.5)*S.width/1000,b=turf.buffer(p,d,{units:'kilometers'});if(!b)break;let coords=b.geometry.type==='Polygon'?b.geometry.coordinates[0]:b.geometry.coordinates[0][0];lines.push(coords.map(([x,y])=>[y,x]))}S.guidanceSets.push({name:'Border passes',kind:'headland',lines});redraw()}

function editGuidanceMenu(){let sets=(S.guidanceSets||[]).map((x,i)=>({x,i})).filter(o=>o.x.kind==='main');if(!sets.length)return alert('There are no saved main guidance lines to edit yet.');open(`<h3>Edit Guidance</h3><p>Select the guidance set you want to recreate or remove.</p><div class="section-list">${sets.map(o=>`<button data-g="${o.i}">${escapeHtml(o.x.name)} • ${o.x.lines.length} lines</button>`).join('')}</div><button id="back">Back</button>`);document.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>editGuidanceSet(+b.dataset.g));$('#back').onclick=fieldScreen}
function editGuidanceSet(i){let set=S.guidanceSets[i];open(`<h3>${escapeHtml(set.name)}</h3><div class="status">${set.lines.length} guidance lines</div><div class="row"><button id="recreate" class="primary">Recreate / Adjust</button><button id="deleteG" class="danger">Delete</button></div><button id="back">Back</button>`);$('#deleteG').onclick=()=>{if(confirm('Delete this guidance set?')){S.guidanceSets.splice(i,1);redraw();fieldScreen()}};$('#recreate').onclick=()=>{S.guidanceSets.splice(i,1);if(set.source==='border'&&Number.isInteger(set.borderIndex)&&S.sections[set.borderIndex]){S._border=set.borderIndex;guidanceOptions('border')}else if(set.source==='ab'&&set.ab&&set.ab.length===2){S._ab=set.ab.map(p=>p.slice());guidanceOptions('ab')}else{redraw();guidanceMenu()}};$('#back').onclick=editGuidanceMenu}
function guidanceMenu(){open(`<h3>Create Guidance</h3><p>Choose how the main guidance direction is created.</p><div class="row"><button id="ab" class="primary">Create A-B Line</button><button id="from">Create from Border</button></div><button id="back">Back</button>`);$('#ab').onclick=()=>{S._ab=[];mode='ab';close();alert('Tap point A, then point B on the map.')};$('#from').onclick=borderList;$('#back').onclick=fieldScreen}
function borderList(){if(!S.sections.length)return alert('Name at least one border section first.');open(`<h3>Create from Border</h3><p>Select the saved border to use as the reference.</p><div class="section-list">${S.sections.map((s,i)=>`<button data-i="${i}">${s.name}</button>`).join('')}</div><button id="back">Back</button>`);document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{S._border=+b.dataset.i;guidanceOptions('border')});$('#back').onclick=guidanceMenu}
function guidanceOptions(source){open(`<h3>Guidance Settings</h3><p>${source==='ab'?'A-B reference':'From '+S.sections[S._border].name}</p><label>Guidance set name<input id="gn" value="${source==='ab'?'Main rows':S.sections[S._border].name+' rows'}"></label><label>Implement width (m)<input id="gw" type="number" step="0.01" value="${S.width||9}"></label><label>Coverage<select id="coverage"><option value="fill">Fill Entire Field</option><option value="count">Set Number of Lines</option></select></label><label id="countLab" class="hidden">Number of lines<input id="gc" type="number" min="1" value="10"></label><button id="preview" class="primary">Preview Guidance</button><button id="back">Back</button>`);$('#coverage').onchange=()=>$('#countLab').classList.toggle('hidden',$('#coverage').value!=='count');$('#preview').onclick=()=>generateGuidance(source);$('#back').onclick=guidanceMenu}
function usablePoly(){let p=poly();if(S.borderPasses>0){let b=turf.buffer(p,-S.borderPasses*S.width/1000,{units:'kilometers'});if(b&&b.geometry.type==='Polygon')return b}return p}
function clipLine(line,p){let out=[];try{let split=turf.lineSplit(line,turf.polygonToLine(p));for(const f of split.features){let mid=turf.along(f,turf.length(f)/2);if(turf.booleanPointInPolygon(mid,p))out.push(f)}}catch{}return out}
function generateGuidance(source){let width=+$('#gw').value||9,count=$('#coverage').value==='count'?Math.max(1,+$('#gc').value||1):999,name=$('#gn').value.trim()||'Guidance',p=usablePoly(),lines=[];if(source==='ab'){let [aa,bb]=S._ab.map(([y,x])=>turf.point([x,y])),bearing=turf.bearing(aa,bb),box=turf.bbox(p),diag=turf.distance([box[0],box[1]],[box[2],box[3]],{units:'meters'}),center=turf.center(p);let offsets=[0];for(let i=1;i<1000;i++)offsets.push(i*width,-i*width);for(const off of offsets){if(lines.length>=count)break;let c=turf.destination(center,off,bearing+90,{units:'meters'}),a=turf.destination(c,diag*2,bearing+180,{units:'meters'}),b=turf.destination(c,diag*2,bearing,{units:'meters'}),parts=clipLine(turf.lineString([a.geometry.coordinates,b.geometry.coordinates]),p);for(const f of parts){lines.push(f.geometry.coordinates.map(([x,y])=>[y,x]));if(lines.length>=count)break}if($('#coverage').value==='fill'&&Math.abs(off)>diag*1.5)break}}else{let s=S.sections[S._border],base=turf.lineString(idxs(s.start,s.end).map(i=>[S.boundary[i][1],S.boundary[i][0]])),start=(S.borderPasses+.5)*width;for(let i=0;i<1000&&lines.length<count;i++){let found=false,offset=start+i*width;for(const sign of [1,-1]){let off=turf.lineOffset(base,sign*offset,{units:'meters'}),parts=clipLine(off,p);if(parts.length){found=true;for(const f of parts){lines.push(f.geometry.coordinates.map(([x,y])=>[y,x]));if(lines.length>=count)break}break}}if($('#coverage').value==='fill'&&!found&&i>3)break}}S.width=width;S.guidanceSets.push({name,kind:'main',source,lines,borderIndex:source==='border'?S._border:null,ab:source==='ab'?(S._ab||[]).map(p=>p.slice()):null});redraw();open(`<h3>Guidance Preview</h3><div class="status">${name}<br>${lines.length} guidance lines • ${width.toFixed(2)} m</div><div class="row"><button id="keep" class="primary">Save Guidance</button><button id="remove">Discard</button></div>`);$('#keep').onclick=fieldScreen;$('#remove').onclick=()=>{S.guidanceSets.pop();redraw();guidanceMenu()}}
function exportScreen(){open(`<h3>Export</h3><p>Download the current field, named borders, border passes, and guidance sets.</p><button id="geo" class="primary">Download GeoJSON</button><button id="shp">Download Shapefile ZIP</button><button id="back">Back</button>`);$('#geo').onclick=()=>dl(new Blob([JSON.stringify(fc(),null,2)],{type:'application/json'}),safe(S.name)+'.geojson');$('#shp').onclick=()=>shpwrite.download(fc(),{folder:safe(S.name),types:{polygon:'boundary',line:'lines',point:'points'}});$('#back').onclick=fieldScreen}
function fc(){let f=[turf.polygon([ring()],{type:'boundary',field:S.name})];S.sections.forEach(s=>f.push(turf.lineString(idxs(s.start,s.end).map(i=>[S.boundary[i][1],S.boundary[i][0]]),{type:'border',name:s.name})));S.guidanceSets.forEach(set=>set.lines.forEach((g,i)=>f.push(turf.lineString(g.map(([y,x])=>[x,y]),{type:set.kind,name:set.name,pass:i+1,width_m:S.width}))));return turf.featureCollection(f)}function safe(s){return(s||'field').replace(/[^a-z0-9_-]+/gi,'_')}function dl(blob,n){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=n;a.click()}
function showFieldsHome(){removeHandle();hidePointMenu();mode=null;mapBar.classList.add('hidden');home.classList.add('hidden');let cards=DB.fields.map(f=>{let old=S;S=f;let a=area().toFixed(2);S=old;return `<div class="field-card"><div><b>${escapeHtml(f.name)}</b><small>${a} ha</small></div><div class="field-card-actions"><button data-view="${f.id}">View</button><button data-edit="${f.id}">Edit</button><button data-menu="${f.id}">⋮</button></div></div>`}).join('');open(`<div class="fields-head"><h2>My Fields</h2><button id="newFromList" class="primary">+ New Field</button></div>${cards||'<p>No fields saved yet. Create your first field.</p>'}`);$('#newFromList').onclick=newField;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>openField(+b.dataset.view,false));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openField(+b.dataset.edit,true));document.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>fieldItemMenu(+b.dataset.menu))}
function openField(id,edit){let f=DB.fields.find(x=>x.id===id);if(!f)return;S=f;DB.currentId=id;save();if(S.boundary.length)map.fitBounds(L.latLngBounds(S.boundary),{padding:[45,45],maxZoom:19});if(edit){S.stage='locked';sectionScreen()}else{S.stage='saved';fieldScreen()}redraw()}
function fieldItemMenu(id){let f=DB.fields.find(x=>x.id===id);if(!f)return;open(`<h3>${escapeHtml(f.name)}</h3><button id="deleteField" class="danger">Delete Field</button><button id="back">Back</button>`);$('#deleteField').onclick=()=>{if(confirm(`Delete ${f.name}? This cannot be undone.`)){DB.fields=DB.fields.filter(x=>x.id!==id);if(DB.currentId===id)DB.currentId=null;localStorage.setItem('flbFields',JSON.stringify(DB));S=emptyField();redraw();showFieldsHome()}};$('#back').onclick=showFieldsHome}
showFieldsHome();redraw();
